<a href="https://colab.research.google.com/github/Abdulwadud4/ACCESS-6.0-Data-Science-track/blob/main/linear_regression_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd
whsrs = pd.read_csv("/content/Warehouse_and_Retail_Sales (1).csv")

In [24]:
for col in whsrs.columns:
  if whsrs[col].isna().sum() > 0:
    print(f"{col}: {whsrs[col].isna().sum()} - {whsrs[col].dtype}")
  else:
    print(f"{col} has no missing values")

YEAR has no missing values
MONTH has no missing values
SUPPLIER: 167 - object
ITEM CODE has no missing values
ITEM DESCRIPTION has no missing values
ITEM TYPE: 1 - object
RETAIL SALES: 3 - float64
RETAIL TRANSFERS has no missing values
WAREHOUSE SALES has no missing values

In [25]:
whsrs["SUPPLIER"] = whsrs["SUPPLIER"].fillna(whsrs["SUPPLIER"].mode()[0])
whsrs["ITEM TYPE"] = whsrs["ITEM TYPE"].fillna(whsrs["ITEM TYPE"].mode()[0])
whsrs["RETAIL SALES"] = whsrs["RETAIL SALES"].fillna(whsrs["RETAIL SALES"].median())

In [26]:
for col in whsrs.columns:
  if whsrs[col].isna().sum() > 0:
    print(f"{col}: {whsrs[col].isna().sum()} - {whsrs[col].dtype}")
  else:
    print(f"{col} has no missing values")

YEAR has no missing values
MONTH has no missing values
SUPPLIER has no missing values
ITEM CODE has no missing values
ITEM DESCRIPTION has no missing values
ITEM TYPE has no missing values
RETAIL SALES has no missing values
RETAIL TRANSFERS has no missing values
WAREHOUSE SALES has no missing values

In [27]:
for col in whsrs.columns:
  if whsrs[col].isna().sum() > 0:
    print(f"{col}: {whsrs[col].isna().sum()} - {whsrs[col].dtype}")

In [28]:
whsrs["ITEM DESCRIPTION"] = whsrs["ITEM DESCRIPTION"].fillna(whsrs["ITEM DESCRIPTION"].mode()[0])
whsrs["RETAIL TRANSFERS"] = whsrs["RETAIL TRANSFERS"].fillna(whsrs["RETAIL TRANSFERS"].mode()[0])
whsrs["WAREHOUSE SALES"] = whsrs["WAREHOUSE SALES"].fillna(whsrs["WAREHOUSE SALES"].median())

In [29]:
for col in whsrs.columns:
  if whsrs[col].isna().sum() > 0:
    print(f"{col}: {whsrs[col].isna().sum()} - {whsrs[col].dtype}")
  else:
    print(f"{col} has no missing values")

YEAR has no missing values
MONTH has no missing values
SUPPLIER has no missing values
ITEM CODE has no missing values
ITEM DESCRIPTION has no missing values
ITEM TYPE has no missing values
RETAIL SALES has no missing values
RETAIL TRANSFERS has no missing values
WAREHOUSE SALES has no missing values

In [30]:
#creating new features based on what we have in the dataset
whsrs['TOTAL SALES'] = whsrs['WAREHOUSE SALES'] + whsrs['RETAIL SALES'] # total sales

#absolute value of total sales -> this will help identify high-activity products or locations even when returns are involved
whsrs["ABS_TOTAL_SALES"] = whsrs["TOTAL SALES"].abs()


#sales direction
whsrs["SALES_DIRECTION"] = whsrs["TOTAL SALES"].apply(
    lambda x: "Positive Sales" if x > 0 else ("No Activity" if x == 0 else "Returns/Adjustment")
)

#creating a new months column with actual name based on the original MONTH column
mapping_months = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}

whsrs["MONTH_NAME"] = whsrs["MONTH"].map(mapping_months)

In [31]:
whsrs.tail(10)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,TOTAL SALES,ABS_TOTAL_SALES,SALES_DIRECTION,MONTH_NAME
307635,2020,9,REPUBLIC NATIONAL DISTRIBUTING CO,99694,PAULANER SALVATORE 4/6NR - 12OZ,BEER,0.25,2.0,5.00,5.25,5.25,Positive Sales,September
307636,2020,9,SIERRA NEVADA BREWING CO,99708,SIERRA NEVADA PALE ALE 2/12 NR - 12OZ,BEER,35.00,19.0,288.00,323.00,323.00,Positive Sales,September
307637,2020,9,SIERRA NEVADA BREWING CO,99716,SIERRA NEVADA PALE ALE 12/24OZ NR - 24OZ,BEER,0.00,0.0,58.00,58.00,58.00,Positive Sales,September
307638,2020,9,LEGENDS LTD,99730,ERDINGER WEISS NR 12/CS - 16.9OZ,BEER,0.00,0.0,4.00,4.00,4.00,Positive Sales,September
307639,2020,9,MILLER BREWING COMPANY,99740,MOLSON GOLDEN 2/12 LNNR - 12OZ,BEER,5.50,9.0,108.50,114.00,114.00,Positive Sales,September
307640,2020,9,LEGENDS LTD,99753,DUTCHESS DE BOURGOGNE NR - 750ML,BEER,0.00,0.0,5.00,5.00,5.00,Positive Sales,September
307641,2020,9,ANHEUSER BUSCH INC,9997,HOEGAARDEN 4/6NR - 12OZ,BEER,66.12,37.0,240.75,306.87,306.87,Positive Sales,September
307642,2020,9,COASTAL BREWING COMPANY LLC,99970,DOMINION OAK BARREL STOUT 4/6 NR - 12OZ,BEER,2.25,0.0,0.00,2.25,2.25,Positive Sales,September
307643,2020,9,BOSTON BEER CORPORATION,99990,SAM ADAMS SUMMER VARIETY 12PK NR,BEER,20.50,0.0,0.00,20.50,20.50,Positive Sales,September
307644,2020,9,REPUBLIC NATIONAL DISTRIBUTING CO,WC,WINE CREDIT,REF,0.00,0.0,-70.00,-70.00,70.00,Returns/Adjustment,September

In [32]:
whsrs['SALES_DIRECTION'].value_counts()

SALES_DIRECTION
Positive Sales        303786
No Activity             3129
Returns/Adjustment       730
Name: count, dtype: int64

In [33]:
whsrs['MONTH'] = pd.to_datetime(whsrs['MONTH'])
print("Converted 'MONTH' column to datetime objects.")

Converted 'MONTH' column to datetime objects.

In [34]:
whsrs.head(10)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,TOTAL SALES,ABS_TOTAL_SALES,SALES_DIRECTION,MONTH_NAME
0,2020,1970-01-01 00:00:00.000000001,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0,2.00,2.00,Positive Sales,January
1,2020,1970-01-01 00:00:00.000000001,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0,4.00,4.00,Positive Sales,January
2,2020,1970-01-01 00:00:00.000000001,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0,1.00,1.00,Positive Sales,January
3,2020,1970-01-01 00:00:00.000000001,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0,1.00,1.00,Positive Sales,January
4,2020,1970-01-01 00:00:00.000000001,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0,0.82,0.82,Positive Sales,January
5,2020,1970-01-01 00:00:00.000000001,KYSELA PERE ET FILS LTD,100641,CORTENOVA VENETO P/GRIG - 750ML,WINE,2.76,0.0,6.0,8.76,8.76,Positive Sales,January
6,2020,1970-01-01 00:00:00.000000001,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.08,1.0,1.0,1.08,1.08,Positive Sales,January
7,2020,1970-01-01 00:00:00.000000001,BROWN-FORMAN BEVERAGES WORLDWIDE,1008,JACK DANIELS COUNTRY COCKTAIL SOUTHERN PEACH -...,BEER,0.00,0.0,2.0,2.00,2.00,Positive Sales,January
8,2020,1970-01-01 00:00:00.000000001,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,6.41,4.0,0.0,6.41,6.41,Positive Sales,January
9,2020,1970-01-01 00:00:00.000000001,INTERNATIONAL CELLARS LLC,101117,KSARA CAB - 750ML,WINE,0.33,1.0,2.0,2.33,2.33,Positive Sales,January

In [35]:
#check columns
whsrs.columns

Index(['YEAR', 'MONTH', 'SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION',
       'ITEM TYPE', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES',
       'TOTAL SALES', 'ABS_TOTAL_SALES', 'SALES_DIRECTION', 'MONTH_NAME'],
      dtype='object')

In [47]:
#defining X and y
y = whsrs["TOTAL SALES"] #target variable
x = whsrs.drop(columns = ["TOTAL SALES", "ITEM CODE", "MONTH"], axis = 1) #features

In [37]:
whsrs['DAY_OF_WEEK'] = whsrs['MONTH'].dt.day_name()
print("Added 'DAY_OF_WEEK' column with day names.")

Added 'DAY_OF_WEEK' column with day names.

In [38]:
whsrs.head(10)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,TOTAL SALES,ABS_TOTAL_SALES,SALES_DIRECTION,MONTH_NAME,DAY_OF_WEEK
0,2020,1970-01-01 00:00:00.000000001,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0,2.00,2.00,Positive Sales,January,Thursday
1,2020,1970-01-01 00:00:00.000000001,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0,4.00,4.00,Positive Sales,January,Thursday
2,2020,1970-01-01 00:00:00.000000001,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0,1.00,1.00,Positive Sales,January,Thursday
3,2020,1970-01-01 00:00:00.000000001,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0,1.00,1.00,Positive Sales,January,Thursday
4,2020,1970-01-01 00:00:00.000000001,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0,0.82,0.82,Positive Sales,January,Thursday
5,2020,1970-01-01 00:00:00.000000001,KYSELA PERE ET FILS LTD,100641,CORTENOVA VENETO P/GRIG - 750ML,WINE,2.76,0.0,6.0,8.76,8.76,Positive Sales,January,Thursday
6,2020,1970-01-01 00:00:00.000000001,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.08,1.0,1.0,1.08,1.08,Positive Sales,January,Thursday
7,2020,1970-01-01 00:00:00.000000001,BROWN-FORMAN BEVERAGES WORLDWIDE,1008,JACK DANIELS COUNTRY COCKTAIL SOUTHERN PEACH -...,BEER,0.00,0.0,2.0,2.00,2.00,Positive Sales,January,Thursday
8,2020,1970-01-01 00:00:00.000000001,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,6.41,4.0,0.0,6.41,6.41,Positive Sales,January,Thursday
9,2020,1970-01-01 00:00:00.000000001,INTERNATIONAL CELLARS LLC,101117,KSARA CAB - 750ML,WINE,0.33,1.0,2.0,2.33,2.33,Positive Sales,January,Thursday

In [39]:
whsrs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307645 entries, 0 to 307644
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   YEAR              307645 non-null  int64
 1   MONTH             307645 non-null  datetime64[ns]
 2   SUPPLIER          307645 non-null  object
 3   ITEM CODE         307645 non-null  object
 4   ITEM DESCRIPTION  307645 non-null  object
 5   ITEM TYPE         307645 non-null  object
 6   RETAIL SALES      307645 non-null  float64
 7   RETAIL TRANSFERS  307645 non-null  float64
 8   WAREHOUSE SALES   307645 non-null  float64
 9   TOTAL SALES       307645 non-null  float64
 10  ABS_TOTAL_SALES   307645 non-null  float64
 11  SALES_DIRECTION   307645 non-null  object
 12  MONTH_NAME        307645 non-null  object
 13  DAY_OF_WEEK       307645 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 32.9+ MB

In [40]:
categorical_features = whsrs.select_dtypes(include=["object"]).columns
numerical_features = whsrs.select_dtypes(include = ["float64", "int64"]).columns


categorical_features, numerical_features

(Index(['SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION', 'ITEM TYPE',
        'SALES_DIRECTION', 'MONTH_NAME', 'DAY_OF_WEEK'],
       dtype='object'),
 Index(['YEAR', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES',
        'TOTAL SALES', 'ABS_TOTAL_SALES'],
       dtype='object'))

In [41]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [42]:
#scaling
scale = StandardScaler()
encoder = OneHotEncoder(handle_unknown = "ignore")


#column transformer
preprocessor = ColumnTransformer(
    transformers = [
        ("num", scale, numerical_features),
        ("cat", encoder, categorical_features)
    ]
)

In [44]:
y

0           2.00
1           4.00
2           1.00
3           1.00
4           0.82
           ...
307640      5.00
307641    306.87
307642      2.25
307643     20.50
307644    -70.00
Name: TOTAL SALES, Length: 307645, dtype: float64

In [48]:
x.head()

,YEAR,SUPPLIER,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES,ABS_TOTAL_SALES,SALES_DIRECTION,MONTH_NAME,DAY_OF_WEEK
0,2020,REPUBLIC NATIONAL DISTRIBUTING CO,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0,2.00,Positive Sales,January,Thursday
1,2020,PWSWN INC,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0,4.00,Positive Sales,January,Thursday
2,2020,RELIABLE CHURCHILL LLLP,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0,1.00,Positive Sales,January,Thursday
3,2020,LANTERNA DISTRIBUTORS INC,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0,1.00,Positive Sales,January,Thursday
4,2020,DIONYSOS IMPORTS INC,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0,0.82,Positive Sales,January,Thursday

In [49]:
#split the dataset
x_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [50]:
x_train.shape, X_test.shape, y_train.shape, y_test.shape

((246116, 10), (61529, 10), (246116,), (61529,))

In [55]:
#initializiing the model
lr = LinearRegression()

model = Pipeline(
    steps = [
        ("preprocessor", preprocessor),
        ("regressor", lr)
    ]
)
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['YEAR', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES',
       'TOTAL SALES', 'ABS_TOTAL_SALES'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION', 'ITEM TYPE',
       'SALES_DIRECTION', 'MONTH_NAME', 'DAY_OF_WEEK'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

In [58]:
#initializiing the model
lr = LinearRegression()

model = Pipeline(
    steps = [
        ("preprocessor", preprocessor),
        ("regressor", lr)
    ]
)
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['YEAR', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES',
       'TOTAL SALES', 'ABS_TOTAL_SALES'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION', 'ITEM TYPE',
       'SALES_DIRECTION', 'MONTH_NAME', 'DAY_OF_WEEK'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

In [ ]:
#model training
model.fit(X_train, y_train)